---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Content
  create: all
  match: "*.md"
  templates:
  - page
- type: directory
  path: folder
  label: Folder
  create: documents
  match: "*.md"
  templates:
  - size
  - article
  - page
- type: directory
  path: ".forestry"
  label: Configuration
  create: none
  match: "**/*.yml"
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
